name: Run shot
on: [push]

jobs:
  instrumentationTests:
    name: Screenshot Tests
    runs-on: macos-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Screenshot Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          target: google_apis
          profile: pixel_3a
          disable-animations: true
          script: ./gradlew executeScreenshotTests
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Reports
          path: app/build/reports/
