name: verify snapshot
on: [push]
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  instrumentationTests:
    name: Screenshot Tests
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start emulator
        run: scripts/start_emulator.sh
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Grant execute permission for action command
        run: chmod +x scripts/action_emulator_command.sh
      - name: Run Screenshot Tests
        shell: bash
        run: scripts/action_emulator_command.sh executeScreenshotTests
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Reports
          path: app/build/reports/
